auxiliary_model:
  name: "qwen2_5-vl"
  path: "/home/wangjy/data/Qwen2.5-VL/7B"
  device: "cuda:0"

dataset:
  name: "mm-safebench"
  input_json: "/home/wangjy/exp/JailbreakToolBox/GenData/MM-SafetyBench/output.json"  # JSON 文件路径

viscra:
  vision_token: 151655
  grid_dim: 28
  gaussian_sigma: 14
  attention_block_size: 12
  attention_layer: 18
  output_root: "./attention_mask_12(green)"  # 掩码输出根目录

inference:
  model_name: "Qwen3-VL-32B"
  output_dir: "./viscra_results"

openai:
  base_url: "http://localhost:8000/v1"
  api_key: "EMPTY"